<a href="https://colab.research.google.com/github/Malthr/sembago-ml/blob/main/Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project ID : CH2-PS393

Project Name: Sembago

Project Themes: Food Accessibility, Agribusiness, and Food Security


Project Team Members:

(ML) M324BSY1271 - Syukri Mar-Am - Universitas Tanjungpura

(ML) M359BSY1158 - Mohammad Alif Tuharea - Universitas Palangka Raya

(ML) M131BSX1924 - Nevi Marita Rimadhani - Politeknik Negeri Malang

(CC) C010BSY3251 - Bintang Satrya Leksono - Universitas Indonesia

(CC) C568BKY4423 - Insanu Sholeh Jum Gunawan - Universitas Islam Negeri Walisongo Semarang

(MD) A568BKX4455 - Siti Zikrina Farahdiba - Universitas Islam Negeri Walisongo Semarang

(MD) A248BSY2902 - Farhan Aditya - Universitas Lampung

In [7]:
#Import Package

import pandas as pd
import numpy as np
import pprint

In [2]:
from google.colab import drive

drive.mount('/content/drive')
%cd /content/drive/Shareddrives/Machine Learning CH2-PS393


Mounted at /content/drive
/content/drive/Shareddrives/Machine Learning CH2-PS393


In [ ]:
df_rating = pd.read_csv('dummy_ratings.csv')
display(df_rating)

id_user id_produk id_market  rating
0      b680      a074      b595       4
1      b759      a248      b851       5
2      c196      a356      c044       3
3      c288      a519      c221       1
4      c600      a612      g864       3
..      ...       ...       ...     ...
495    z204      z327      w285       5
496    z303      z420      x399       5
497    z360      z663      y554       4
498    z584      z689      z840       2
499    z647      z717      z874       4

[500 rows x 4 columns]

In [9]:
df_user = pd.read_csv('dummy_produk.csv')
display(df_user)

id_produk id_market nama_produk  stok  Unnamed: 4
0        a074      s685       Bruen    37         NaN
1        a248      j668    Bernhard    42         NaN
2        a356      n829     Effertz    47         NaN
3        a519      s408     Shields    38         NaN
4        a612      s926       White    21         NaN
..        ...       ...         ...   ...         ...
245      z327      h995   Jaskolski    48         NaN
246      z420      g864     Goodwin    29         NaN
247      z663      h995    Bergnaum    28         NaN
248      z689      b595   Rodriguez    37         NaN
249      z717      h995    Franecki    12         NaN

[250 rows x 5 columns]

In [6]:
!pip install -q tensorflow-recommenders
import tensorflow as tf
import tensorflow_recommenders as tfrs

In [11]:
def load_dataset(file_path, features, labels=None):
  df = pd.read_csv(file_path)

  features = df[features]

  if labels:
    labels = df[labels]
    dataset = tf.data.Dataset.from_tensor_slices((dict(features), labels))
  else:
    dataset = tf.data.Dataset.from_tensor_slices(dict(features))

  return dataset

In [12]:
ratings = load_dataset('dummy_ratings.csv', ['id_user', 'id_produk', 'id_market'], ['rating'])
produks = load_dataset('dummy_produk.csv', ['id_produk', 'id_market', 'nama_produk'])

for example in ratings.take(1):
  print("Data : ", example)

for example in produks.take(1):
  print("Data : ", example)

Data :  ({'id_user': <tf.Tensor: shape=(), dtype=string, numpy=b'b680'>, 'id_produk': <tf.Tensor: shape=(), dtype=string, numpy=b'a074'>, 'id_market': <tf.Tensor: shape=(), dtype=string, numpy=b'b595'>}, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([4])>)
Data :  {'id_produk': <tf.Tensor: shape=(), dtype=string, numpy=b'a074'>, 'id_market': <tf.Tensor: shape=(), dtype=string, numpy=b's685'>, 'nama_produk': <tf.Tensor: shape=(), dtype=string, numpy=b'Bruen'>}
